### ISSUE TITLE
No bitwise AND, OR, or XOR operations in IntX for C#  ( '&', '|', and '^' operators)

### ISSUE THREAD

**Issue by SparkDustJoe** [devoyster/IntXLib#2]
Hi, is there any development plan into include bitwise, AND, OR, or XOR operations for your library?

I'm trying to implement a Galois Linear Feedback Shift Register of (almost) arbitrary bit length, but in order to accomplish the actual flipping of bits it requires:
1: Determining least significant bit in register (1 = flip bits) (modulus 2 math handles this, but bitwise AND with the number 1 also works)
2: Shifting the "state" of the machine over 1 bit (shifting right already implemented)
3: If lsb from step 1 was a 1, then flip bits (accomplished by XORing the "state" of the machine with a number of equal bit length in which the bits that represent the "taps" of the shift register are set to 1)
(see https://en.wikipedia.org/wiki/Linear_feedback_shift_register for a more detailed explanation)

So If I have a shift register with 4 taps, of width 16 bits, where the taps are set at bits 16, 14, 13, and 11, I would XOR the 16bit number ('short' in C#) 0xB400 to the state (also a 'short').  Or Binary, that's
1011010000000000.

Currently, if I want to use your library, there are no XOR operations, and so I can't flip the bits of the state of the register without a bunch of extra work that slows the whole process down considerably.

I can help with the development if I know how to get at the "raw" bits or internal integers of the two IntX objects and calculate a result.

Thanks.

**Comment by devoyster** [comment]
Hi Dustin,




Implementing bitwise ops should be simple enough, so I will do it soon. No promises though :)




Best regards,

Andriy Kozachuk

**Comment by SparkDustJoe** [comment]
Thank you, and no rush, this is a side project that I'm experimenting with Linear registers and Non-Linear registers.  The first only requires XOR, the second requires... well... everything :P

**Comment by devoyster** [comment]
Hi,




Btw, with arbitrary-precision integers bitwise XOR and NOT are not that obvious :)




My current plan is to NOT/XOR using 4-byte number boundaries (I store numbers as uint arrays so it's the easiest way - just go and process every uint in array). Other options could be to decide that number ends on its highest byte or even bit but it's a bit harder to implement and I doubt is needed. What would be your thoughts, will my plan work for you?




Btw, I don't store negative numbers in two's complement format, I just store sign as a separate bool field. So for both negative and positive bitwise ops would work exactly the same (and it's a question what to do with sign - probably best is to perform same bitwise op on sign from both numbers). This behavior is different from that for .NET primitive number types, please keep that in mind.




PS: On lib update - I'm going on vacation soon so I will either do it tomorrow (if will have time) or it will be postponed until mid-March




Best regards,

Andriy Kozachuk

**Comment by SparkDustJoe** [comment]
Again, no rush, side project :+1:     Thanks :)

You could probably have a highest-bit or most-significant-bit or bit-width parameter, and mask off any bits above that, preventing weird precision problems.   If you are using a separate boolean SIGN flag, in pure theory that should be the highest bit in the result, so yeah it could get a little messy with dealing with the sign's separately between the two operands, especially when they are of different sizes.  Customarily, during size mismatched operations like these, the biggest number is acted upon by the smaller number (or the bigger number becomes the copy for the result, and then "tweaked" by the other operand).  AND operations it's the opposite since no bit of a higher-order than the highest-order bit in the smaller number should be 1 (if that makes sense... in other words, in an AND operation, the smallest number dictates the size of the result).

Since all the bits are uint's internally, just doing a for(int x = blahblah) { intx_result[x] = intx_a[x] ^ intx_b[x] } should work, and the masking can be done at the end (size-mismatch is most critical during AND operations).

As for NOT, I'm not quite sure if that's done in 2's compliment in native .NET, but in theory it should be an XOR operation with all 1's and an ADD operation to accomplish the same bit-wise result.  So implementing XOR would give you NOT in a sense.  You'd have to be mindful of the highest order bits.

As for bitwise AND and OR, the same internal processing principle should apply as for XOR.

I'm not familiar with the internal structure of the IntX class, and how the uints or control functionality are managed, but doing things in this fashion shouldn't be as messy as bit-shifting or carry add/subtract, the bits don't "move" or affect their "neighbors" so I would think it should be straight-forward, but this isn't my library, and I can only speak in a theoretical fashion.  :)

Thanks again for taking the time.  When you do this update, will you be pushing out an updated NuGet or just the source here?

-Dustin

**Comment by devoyster** [comment]
Hi again,




Yes, implementing bitwise ops is quite simple, simpler than any arithmetic ops for sure. So I guess I will just implement it the simplest way for now, it can be adjusted later if needed.




I will publish new version in NuGet, this change will be big enough for that.




Andriy

**Comment by devoyster** [comment]
Hi,




I had no time to update lib so it will happen somewhere mid-March.




Andriy

**Comment by SparkDustJoe** [comment]
No worries. :)   Also, could I request an "IsOdd" or "IsEven" method?  Basically, just a very quick check if the least significant bit is 1 or 0.  This will speed up simple calculations like when to flip bits in a feedback shift register or getting the output of an FSR rather than doing Modulus math on the ENTIRE (potentially large) register just to find out the value of a single bit.   Thanks.

**Comment by devoyster** [comment]
I have added bitwise operations support, as well as IsOdd flag, to IntX lib version 1.0.1

You can already grab it from NuGet

**Comment by SparkDustJoe** [comment]
That's awesome :)  Thank you :+1:  I'll run a series of tests in my test harness and if I run into any issues, I'll open them as such here on GitHub.

**Comment by michealChin** [comment]
Hi,

This Big integer class is marvelous!
I have compared IntX with BigInteger for a really big number more than 100digit, and IntX is at least 10 times faster than BigInteger. Anyway I just couldn't find the GreatestCommonDivisor method in IntX.

**Comment by devoyster** [comment]
Hi michealChin,

I have no plans to implement GCD myself. You can implement it youself using Euclid algorithm - should not be too complex - or something more sophisticated.

Please consider creating pull request for IntX if you will do.
